version: '3.1'
services: 
    database:
        image: mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: passworddelta
        volumes: 
            - data:/var/lib/
            - mysqldata:/var/lib/mysql
        ports: 
            - "3306:3306"
 
    server:
        build: 
            context: .
            dockerfile: ./Dockerfile
        depends_on:
            - database
        restart: always
        ports:
            - "8000:80"
        volumes: 
            - data:/home/temp
            - ./app/:/var/www/html/
volumes: 
    data:
    mysqldata:
